# Generated by Django 3.2.4 on 2021-07-15 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_quiz_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question_count',
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='correct_answer',
        ),
        migrations.AddField(
            model_name='grade',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='max_score',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='grade',
            field=models.ManyToManyField(to='assessment.Grade'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='quiztaker',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='quiz',
            field=models.ManyToManyField(to='assessment.Quiz'),
        ),
    ]
