# Generated by Django 3.2.4 on 2021-07-09 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='quiztaker',
            new_name='quiz_taker',
        ),
    ]
