# Generated by Django 3.2.4 on 2021-07-15 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_alter_grade_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
