# Generated by Django 3.2.4 on 2021-08-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20210715_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='max_score',
        ),
        migrations.AddField(
            model_name='quiz',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.grade'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='max_score',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='grade',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
