# Generated by Django 3.2.4 on 2021-07-13 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.course'),
        ),
        migrations.AddField(
            model_name='scope',
            name='departmment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.department'),
        ),
        migrations.AddField(
            model_name='scope',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.faculty'),
        ),
        migrations.AddField(
            model_name='scope',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.level'),
        ),
        migrations.AddField(
            model_name='scope',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.programme'),
        ),
        migrations.AlterField(
            model_name='information',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.scope'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.scope'),
        ),
    ]
