# Generated by Django 3.2.4 on 2021-06-30 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.scope'),
        ),
        migrations.AlterField(
            model_name='notices',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
