# Generated by Django 3.2.4 on 2021-06-30 07:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('information', '0002_auto_20210630_0726'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notices',
            new_name='Notice',
        ),
        migrations.AlterModelOptions(
            name='informationimage',
            options={'verbose_name': 'Information Image', 'verbose_name_plural': 'Information Images'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Notice', 'verbose_name_plural': 'Notices'},
        ),
    ]
