# Generated by Django 3.2.4 on 2021-07-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_alter_informationimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informationimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
