# Generated by Django 3.2.4 on 2021-06-30 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_auto_20210630_0731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='information',
            options={'verbose_name': 'Information', 'verbose_name_plural': 'Information'},
        ),
    ]
