# Generated by Django 3.2.4 on 2021-06-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_alter_information_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='description',
            field=models.CharField(default='General', max_length=250),
            preserve_default=False,
        ),
    ]
